feat: new sceneComponent option
react-navigation/drawer pull request #163
Opened 2020-02-14 11:11 UTC by wcandillon

Please provide enough information so that others can review your pull request:

**Motivation**

This allows users to customize drawer animation by providing the ability to set a custom wrapper to the scene.

2020-02-14 20:19 UTC, satya164 requested changes
Thanks for the PR. I think I'd prefer to expose the animated progress value to the screen via context instead of `sceneComponent` prop. We expose similar animation context for stack: https://github.com/react-navigation/react-navigation/blob/424c9469e442d15b31c36ee68d6d98fb419ff9dc/packages/stack/src/index.tsx#L44

2020-02-14 20:19 UTC, satya164 commented on package.json
> +  "version": "2.4.0",
Our versioning is handled by the release process. So revert this change

2020-02-17 14:21 UTC, wcandillon commented
Exposing the progress animation node via the context would be great but we would still need to wrap manually all of our screens with a container that can use this animation node to perform some animation. What are your thoughts on this? Thank you for looking into it.

2020-02-25 11:23 UTC, satya164 commented
I think it's ok, you can create a HOC/wrapper to reduce the repetition. Wrapping screens in a custom view isn't something a lib should do imo. It makes it easier to break things and may also conflict with any animation options that we want to add in future.

PS: this repo is being archived. Please send a PR here https://github.com/react-navigation/react-navigation/tree/4.x/packages/drawer

2020-02-25 11:23 UTC, closed without merging